
#define W3C_PACKAGE "w3c-libwww"
#define W3C_VERSION "5.4.0"
#define PACKAGE "w3c-libwww"
#define VERSION "5.4.0"
#define TELNET_PROGRAM "telnet"
#define RLOGIN_PROGRAM "rlogin"
#define RESOLV_CONF "/etc/resolv.conf"
#define CACHE_FILE_PREFIX "/usr/wsrc/"
#define HAVE_LIBDL 1
#define HAVE_ARPA_INET_H 1
#define HAVE_SYS_ERRNO_H 1
#define HAVE_ERRNO_H 1
#define HAVE_NETINET_IN_H 1
#define HAVE_NETINET_TCP_H 1
#define HAVE_SYS_FCNTL_H 1
#define HAVE_FCNTL_H 1
#define HAVE_SYS_FILE_H 1
#define HAVE_SYS_IOCTL_H 1
#define HAVE_SYS_IPC_H 1
#define HAVE_LIMITS_H 1
#define HAVE_SYS_RESOURCE_H 1
#define HAVE_SYS_SELECT_H 1
#define HAVE_SYS_SOCKET_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_SYSLOG_H 1
#define HAVE_SYS_TIME_H 1
#define HAVE_TIME_H 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_SYS_UNISTD_H 1
#define HAVE_UNISTD_H 1
#define HAVE_CTYPE_H 1
#define HAVE_CURSES_H 1
#define HAVE_GRP_H 1
#define HAVE_MALLOC_H 1
#define HAVE_MEMORY_H 1
#define HAVE_NETDB_H 1
#define HAVE_PWD_H 1
#define HAVE_REGEX_H 1
#define HAVE_STDIO_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_STRINGS_H 1
#define HAVE_TERMIOS_H 1
#define HAVE_DIRENT_H 1
#define STDC_HEADERS 1
#define HAVE_SYS_WAIT_H 1
#define TIME_WITH_SYS_TIME 1
#define GETGROUPS_T gid_t
#define RETSIGTYPE void
#define BOOLEAN char
#define SIZEOF_CHAR 1
